import { Task } from '@/features/tasks/tasks.types';

export const mockTasks: Task[] = [
  {
    id: 'task-1',
    title: 'Set up CI pipeline for staging',
    description: 'Configure GitHub Actions to deploy to staging on merge to develop.',
    status: 'backlog',
    priority: 'medium',
    position: 1000,
    dueDate: null,
    startDate: null,
    creatorId: 'user-1',
    projectId: 'project-1',
    parentTaskId: null,
    assignees: [{ id: 'user-2', username: 'jsmith', fullName: 'Jane Smith', avatarUrl: null }],
    labels: [{ id: 'label-1', name: 'DevOps', color: '#94A3B8' }],
    createdAt: '2026-08-10T09:00:00.000Z',
    updatedAt: '2026-08-10T09:00:00.000Z',
  },
  {
    id: 'task-2',
    title: 'Design onboarding flow wireframes',
    description: null,
    status: 'backlog',
    priority: 'low',
    position: 2000,
    dueDate: '2026-09-01',
    startDate: null,
    creatorId: 'user-1',
    projectId: 'project-1',
    parentTaskId: null,
    assignees: [],
    labels: [{ id: 'label-2', name: 'Design', color: '#A855F7' }],
    createdAt: '2026-08-11T09:00:00.000Z',
    updatedAt: '2026-08-11T09:00:00.000Z',
  },
  {
    id: 'task-3',
    title: 'Fix fractional index rebalance edge case',
    description: 'Positions can get too close together after many reorders.',
    status: 'todo',
    priority: 'high',
    position: 1000,
    dueDate: '2026-08-25',
    startDate: '2026-08-20',
    creatorId: 'user-2',
    projectId: 'project-1',
    parentTaskId: null,
    assignees: [{ id: 'user-1', username: 'ritik', fullName: 'Ritik Rawat', avatarUrl: null }],
    labels: [{ id: 'label-3', name: 'Bug', color: '#EF4444' }],
    createdAt: '2026-08-12T09:00:00.000Z',
    updatedAt: '2026-08-15T09:00:00.000Z',
  },
  {
    id: 'task-4',
    title: 'Write API docs for invite links',
    description: null,
    status: 'todo',
    priority: 'no_priority',
    position: 2000,
    dueDate: null,
    startDate: null,
    creatorId: 'user-1',
    projectId: 'project-1',
    parentTaskId: null,
    assignees: [
      { id: 'user-1', username: 'ritik', fullName: 'Ritik Rawat', avatarUrl: null },
      { id: 'user-2', username: 'jsmith', fullName: 'Jane Smith', avatarUrl: null },
    ],
    labels: [],
    createdAt: '2026-08-13T09:00:00.000Z',
    updatedAt: '2026-08-13T09:00:00.000Z',
  },
  {
    id: 'task-5',
    title: 'Implement drag-and-drop reorder on Kanban board',
    description: 'Wire up the frontend to call PATCH /tasks/:id/reorder.',
    status: 'in_progress',
    priority: 'urgent',
    position: 1000,
    dueDate: '2026-08-22',
    startDate: '2026-08-18',
    creatorId: 'user-1',
    projectId: 'project-1',
    parentTaskId: null,
    assignees: [{ id: 'user-1', username: 'ritik', fullName: 'Ritik Rawat', avatarUrl: null }],
    labels: [
      { id: 'label-4', name: 'Frontend', color: '#3B82F6' },
      { id: 'label-3', name: 'Bug', color: '#EF4444' },
    ],
    createdAt: '2026-08-14T09:00:00.000Z',
    updatedAt: '2026-08-19T09:00:00.000Z',
  },
  {
    id: 'task-6',
    title: 'Review PR: task assignee permissions',
    description: null,
    status: 'in_review',
    priority: 'medium',
    position: 1000,
    dueDate: null,
    startDate: null,
    creatorId: 'user-2',
    projectId: 'project-1',
    parentTaskId: null,
    assignees: [{ id: 'user-2', username: 'jsmith', fullName: 'Jane Smith', avatarUrl: null }],
    labels: [{ id: 'label-4', name: 'Frontend', color: '#3B82F6' }],
    createdAt: '2026-08-15T09:00:00.000Z',
    updatedAt: '2026-08-18T09:00:00.000Z',
  },
  {
    id: 'task-7',
    title: 'Set up Supabase Storage bucket for attachments',
    description: 'Private bucket, signed URLs only.',
    status: 'done',
    priority: 'medium',
    position: 1000,
    dueDate: '2026-08-10',
    startDate: '2026-08-05',
    creatorId: 'user-1',
    projectId: 'project-1',
    parentTaskId: null,
    assignees: [{ id: 'user-1', username: 'ritik', fullName: 'Ritik Rawat', avatarUrl: null }],
    labels: [{ id: 'label-1', name: 'DevOps', color: '#94A3B8' }],
    createdAt: '2026-08-05T09:00:00.000Z',
    updatedAt: '2026-08-10T09:00:00.000Z',
  },
  {
    id: 'task-8',
    title: 'Migrate lockfile off pnpm 11',
    description: null,
    status: 'done',
    priority: 'high',
    position: 2000,
    dueDate: null,
    startDate: null,
    creatorId: 'user-1',
    projectId: 'project-1',
    parentTaskId: null,
    assignees: [],
    labels: [],
    createdAt: '2026-08-16T09:00:00.000Z',
    updatedAt: '2026-08-17T09:00:00.000Z',
  },
];
